from core.config.defaults import (
    DEFAULT_BRAZIL_BBOX_PATH,
    DEFAULT_CAR_PUBLIC_API_BASE,
    DEFAULT_DOWNLOAD_ARCHIVE_BASE,
    DEFAULT_DOWNLOAD_EXTRACT_BASE,
    DEFAULT_MUNICIPALITIES_BASE_PATH,
)

__all__ = [
    "DEFAULT_BRAZIL_BBOX_PATH",
    "DEFAULT_CAR_PUBLIC_API_BASE",
    "DEFAULT_DOWNLOAD_ARCHIVE_BASE",
    "DEFAULT_DOWNLOAD_EXTRACT_BASE",
    "DEFAULT_MUNICIPALITIES_BASE_PATH",
]
