from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

INGEST_WORKBOOK_PATH = PROJECT_ROOT / "input" / "st_Ingest_parameter.xlsx"
INGEST_SHEET_NAME = "datas"
DICTIONARIES_SHEET_NAME = "dictionaries"
INGEST_READY_STATUS = "Waiting Update"

OUTPUT_BASE = PROJECT_ROOT / "output"

DEFAULT_CAR_PUBLIC_API_BASE = "https://consulta.car.gov.br/api"
DEFAULT_DOWNLOAD_EXTRACT_BASE = PROJECT_ROOT / "input" / "downloads"
DEFAULT_DOWNLOAD_ARCHIVE_BASE = DEFAULT_DOWNLOAD_EXTRACT_BASE / "_archives"
DEFAULT_MUNICIPALITIES_BASE_PATH = (
    r"M:\COE_Digital\coe_digital_data\temp\municipios\2023\BR_Municipios_2023.shp"
)

CAR_PUBLIC_API_BASE = DEFAULT_CAR_PUBLIC_API_BASE
DOWNLOAD_ARCHIVE_BASE = DEFAULT_DOWNLOAD_ARCHIVE_BASE
DOWNLOAD_EXTRACT_BASE = DEFAULT_DOWNLOAD_EXTRACT_BASE
CAR_DOWNLOAD_EXTRACT_BASE = DOWNLOAD_EXTRACT_BASE

RULES_BASE = PROJECT_ROOT / "rules"
DEFAULT_RULE_PROFILE = "default"

REQUIRES_PYTHON = ">=3.14"

BATCH_SIZE = 50000
SPATIAL_TRANSFORM_CHUNK_SIZE = 5000

CRS_WGS84 = "EPSG:4326"
CRS_EQUAL_AREA = "EPSG:5880"
DEFAULT_INPUT_CRS = "EPSG:4674"

ID_FIELD = "acm_id"
AREA_FIELD = "acm_a_ha"
PERIMETER_FIELD = "acm_prm_km"
LONGITUDE_FIELD = "acm_long"
LATITUDE_FIELD = "acm_lat"

GEOM_DUPLICATES_LAYER = "duplicados_geometrias"
OGC_INVALID_LAYER = "geometrias_invalidas_ogc"
OGC_REASON_FIELD = "ogc_motivo"

ENABLE_ATTRIBUTE_DUPLICATE_REPORT = True
ENABLE_GEOMETRIC_DUPLICATE_REPORT = True
ENABLE_OGC_INVALID_REPORT = True
ENABLE_GROUP_CONSOLIDATION = False
KEEP_INDIVIDUAL_OUTPUTS_WHEN_GROUPING = False

USE_ARROW_IO = True
INTERACTIVE_ATTRIBUTE_REVIEW = False
