from core.rules.contracts import PROFILE_DATA_KEYS


PROFILE_COMPONENT = "profile.json"
INPUT_SCHEMA_COMPONENT = "input_schema.json"
DOMAINS_COMPONENT = "domains.json"
RELATIONS_COMPONENT = "relations.json"
TREATMENT_COMPONENT = "treatment.json"
STYLE_COMPONENT = "style.json"

PROFILE_COMPONENT_FILES = {
    PROFILE_COMPONENT,
    INPUT_SCHEMA_COMPONENT,
    DOMAINS_COMPONENT,
    RELATIONS_COMPONENT,
    TREATMENT_COMPONENT,
    STYLE_COMPONENT,
}
